// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY5o9B4P4fbzSF4G0v8a0uXxPcSzl7mPI',
    appId: '1:732201591083:web:77fbfe652aad61ce5a656e',
    messagingSenderId: '732201591083',
    projectId: 'testfirebase-3bfcc',
    authDomain: 'testfirebase-3bfcc.firebaseapp.com',
    storageBucket: 'testfirebase-3bfcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-KqBQTo_f8iQQ_IFviUPPDan5MnXGp18',
    appId: '1:732201591083:android:e89af2eae4413c4c5a656e',
    messagingSenderId: '732201591083',
    projectId: 'testfirebase-3bfcc',
    storageBucket: 'testfirebase-3bfcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAInRnYa52ZrkdtxZ1wlnFUfMAlOMntV_8',
    appId: '1:732201591083:ios:8e26775f42d18f255a656e',
    messagingSenderId: '732201591083',
    projectId: 'testfirebase-3bfcc',
    storageBucket: 'testfirebase-3bfcc.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAInRnYa52ZrkdtxZ1wlnFUfMAlOMntV_8',
    appId: '1:732201591083:ios:f995aca1ee3327d95a656e',
    messagingSenderId: '732201591083',
    projectId: 'testfirebase-3bfcc',
    storageBucket: 'testfirebase-3bfcc.appspot.com',
    iosBundleId: 'com.example.testFirebase.RunnerTests',
  );
}
